### ISSUE TITLE
Integration with spl-token

### ISSUE THREAD

**Issue by metaproph3t** [kevinheavey/solana-bankrun#3]
It would be nice to be able to call the spl-token functions, such as the following:
```
underlyingTokenMint = await token.createMint(
      provider.connection.banksClient,
      payer,
      underlyingMintAuthority.publicKey,
      null,
      8
);
```
I think this would require implementing some more of the functions on web3.js' `Connection`, such as `getMinimumBalanceForRentExemption`

**Comment by kevinheavey** [comment]
Making `createMint` work as-is would require hacks for `getMinimumBalanceForRentExemptMint` and `sendAndConfirmTransaction` which would be quite ugly and not compatible with TypeScript.

I'd recommend just rebuilding the transaction like they build it:

```
    const transaction = new Transaction().add(
        SystemProgram.createAccount({
            fromPubkey: payer.publicKey,
            newAccountPubkey: keypair.publicKey,
            space: MINT_SIZE,
            lamports,
            programId,
        }),
        createInitializeMint2Instruction(keypair.publicKey, decimals, mintAuthority, freezeAuthority, programId)
    );
```

If you want to calculate the rent you can do it with `(await banksClient.getRent()).minimumBalance(MINT_SIZE)`. Or you could just stick a large number in the `lamports` field if you're happy to skip the rent calculation step.

I would like if there were SPL Token helpers for `solana-program-test` though. Then I'd be happy to wrap them in `solana-bankrun` or an extension library

**Comment by metaproph3t** [comment]
Huh, getting a fairly non-informative error from doing `(await banksClient.getRent()).minimumBalance(MINT_SIZE)`:
```
      at Context.<anonymous> (tests/conditionalVault.ts:59:35)
      at Generator.next (<anonymous>)
      at fulfilled (tests/conditionalVault.ts:28:58)
```

**Comment by kevinheavey** [comment]
Oh what about `(await banksClient.getRent()).minimumBalance(BigInt(MINT_SIZE))`?

**Comment by metaproph3t** [comment]
Tried that one, it tells me that BigInts must be explicitly converted

Turns out that BigInts and bigints [are different](https://stackoverflow.com/questions/76477290/what-is-the-difference-between-bigint-lowercase-and-bigint). Ah JS, the most well-designed language

**Comment by kevinheavey** [comment]
Isn't MINT_LAYOUT just a regular `number`?

**Comment by metaproph3t** [comment]
Yep, it was something w/ BigInts but unrelated to that line. Just on one test now supported, I got test time down from 4s to 80ms - this is awesome! 

There are some small footguns I've run into (e.g., you have to do context initialization in a `before` function rather than just inside the `describe` block for some reason), so I think I'll publish a gist of my test file as an example migration from anchor to bankrun when I'm done. Relatedly, how do I stop these debug and info messages from getting sent to stdout?

**Comment by kevinheavey** [comment]
These come from the underlying Rust libraries. Use the RUST_LOG env var to silence them e.g. `RUST_LOG= jest --runInBand`

**Comment by yanmarinich** [comment]
these are createSpl and airdropSol functions maybe it can help someone

```
import {
  MINT_SIZE,
  TOKEN_PROGRAM_ID,
  createInitializeMint2Instruction,
} from "@solana/spl-token";
import {
  Keypair,
  LAMPORTS_PER_SOL,
  PublicKey,
  SystemProgram,
  Transaction,
} from "@solana/web3.js";
import { BanksClient, ProgramTestContext } from "solana-bankrun";

export async function createSplToken(
  banksClient: BanksClient,
  payer: Keypair,
  decimals: number,
  mintKeypair: Keypair
) {
  const rent = await banksClient.getRent();
  const rentExemptBalance = rent.minimumBalance(BigInt(MINT_SIZE));

  const transaction = new Transaction().add(
    SystemProgram.createAccount({
      fromPubkey: payer.publicKey,
      newAccountPubkey: mintKeypair.publicKey,
      space: MINT_SIZE,
      lamports: Number(rentExemptBalance),
      programId: TOKEN_PROGRAM_ID,
    }),
    createInitializeMint2Instruction(
      mintKeypair.publicKey,
      decimals,
      payer.publicKey,
      payer.publicKey,
      TOKEN_PROGRAM_ID
    )
  );

  const blockhash = await banksClient.getLatestBlockhash();
  transaction.recentBlockhash = blockhash[0];
  transaction.feePayer = payer.publicKey;
  transaction.sign(payer, mintKeypair);
  await banksClient.processTransaction(transaction);

  return mintKeypair.publicKey;
}

export async function airdropSol(
  context: ProgramTestContext,
  address: PublicKey,
  amount: number
) {
  const lamports = amount * LAMPORTS_PER_SOL;

  const accountInfo = await context.banksClient.getAccount(address);

  const newBalance =
    BigInt(accountInfo ? accountInfo.lamports : 0) + BigInt(lamports);

  context.setAccount(address, {
    lamports: Number(newBalance),
    data: Buffer.alloc(0),
    owner: PublicKey.default,
    executable: false,
  });

  return newBalance;
}
```
